import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const scriptDirectory = dirname(fileURLToPath(import.meta.url));
const mcpDirectory = resolve(scriptDirectory, "..");
const repositoryDirectory = resolve(mcpDirectory, "..");
const allowlistPath = resolve(mcpDirectory, "catalog.allowlist.json");
const defaultOutputPath = resolve(
  mcpDirectory,
  "src/generated/catalog.ts",
);

function parseFrontMatter(source, id) {
  const match = source.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!match) {
    throw new Error(`skills/${id}/SKILL.md is missing YAML front matter`);
  }

  const [, frontMatter, markdown] = match;
  const description = readFrontMatterValue(frontMatter, "description");
  const heading = markdown.match(/^#\s+(.+)$/m)?.[1]?.trim();

  if (!description) {
    throw new Error(`skills/${id}/SKILL.md is missing a description`);
  }

  return {
    title: heading ?? titleFromId(id),
    description,
    markdown: markdown.trim(),
  };
}

function readFrontMatterValue(frontMatter, key) {
  const lines = frontMatter.split(/\r?\n/);
  const start = lines.findIndex((line) => line.startsWith(`${key}:`));
  if (start === -1) return "";

  const initial = lines[start].slice(key.length + 1).trim();
  if (initial && initial !== "|" && initial !== ">") {
    return initial.replace(/^['"]|['"]$/g, "").trim();
  }

  const values = [];
  for (let index = start + 1; index < lines.length; index += 1) {
    const line = lines[index];
    if (/^[a-zA-Z][\w-]*:/.test(line)) break;
    if (line.trim()) values.push(line.trim());
  }
  return values.join(" ").trim();
}

function titleFromId(id) {
  return id
    .split("-")
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

const nonPortablePattern =
  /\.great-pm\/|\$\{CLAUDE_PLUGIN_ROOT\}|Agent\(|\bBash\b|(?:^|[\s`])\/pm-[a-z]|(?:^|[\s`])bd\s|```(?:bash|sh|shell)|\bscripts\//im;

function makePortable(source) {
  return source
    .replace(
      /`?(?:~\/)?\.great-pm\/[^`\s,)]+`?/g,
      "the related project artifact",
    )
    .replace(
      /the Open-Decision Register \(`bd` issue, label `open-decision`\)/g,
      "the team's Open-Decision Register",
    )
    .replace(/\/pm-promote\s+--gate=strategy/g, "the strategy approval gate")
    .replace(/\/pm-cost/g, "the cost forecast")
    .replace(/\/pm-burn/g, "the burn-rate report")
    .replace(/\/pm-digest/g, "the product digest");
}

function assertPortable(source, label) {
  const match = source.match(nonPortablePattern);
  if (match) {
    throw new Error(
      `${label} contains a non-portable public MCP reference: ${match[0].trim()}`,
    );
  }
}

async function buildCatalog() {
  const outputArgument = process.argv.find((argument) =>
    argument.startsWith("--output="),
  );
  const outputPath = outputArgument
    ? resolve(process.cwd(), outputArgument.slice("--output=".length))
    : defaultOutputPath;

  const allowlist = JSON.parse(await readFile(allowlistPath, "utf8"));
  const seen = new Set();
  const methods = [];

  for (const entry of allowlist.methods) {
    if (seen.has(entry.id)) {
      throw new Error(`Duplicate catalog method ID: ${entry.id}`);
    }
    seen.add(entry.id);

    const sourcePath = resolve(
      repositoryDirectory,
      "skills",
      entry.id,
      "SKILL.md",
    );
    const parsed = parseFrontMatter(
      await readFile(sourcePath, "utf8"),
      entry.id,
    );

    const description = makePortable(parsed.description);
    const markdown = makePortable(parsed.markdown);
    assertPortable(description, `Method ${entry.id} description`);
    assertPortable(markdown, `Method ${entry.id} Markdown`);

    methods.push({
      id: entry.id,
      ...parsed,
      description,
      markdown,
      stage: entry.stage,
      tags: entry.tags,
    });
  }

  const templates = await readContentEntries(allowlist.templates, "template");
  const docs = await readContentEntries(allowlist.docs, "document");
  const output = [
    "// Generated by scripts/build-catalog.mjs. Do not edit manually.",
    'import type { GeneratedContent, GeneratedMethod } from "../catalog/types";',
    "",
    `export const generatedMethods = ${JSON.stringify(methods, null, 2)} as const satisfies readonly GeneratedMethod[];`,
    "",
    `export const generatedTemplates = ${JSON.stringify(templates, null, 2)} as const satisfies readonly GeneratedContent[];`,
    "",
    `export const generatedDocs = ${JSON.stringify(docs, null, 2)} as const satisfies readonly GeneratedContent[];`,
    "",
  ].join("\n");

  await mkdir(dirname(outputPath), { recursive: true });
  await writeFile(outputPath, output, "utf8");
}

async function readContentEntries(entries, label) {
  const seen = new Set();
  const contentEntries = [];

  for (const entry of entries) {
    if (seen.has(entry.id)) {
      throw new Error(`Duplicate ${label} ID: ${entry.id}`);
    }
    seen.add(entry.id);
    if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(entry.id)) {
      throw new Error(`Invalid ${label} ID: ${entry.id}`);
    }

    const markdown = makePortable(
      (await readFile(
        resolve(repositoryDirectory, entry.path),
        "utf8",
      )).trim(),
    );
    assertPortable(markdown, `${label} ${entry.id} Markdown`);

    contentEntries.push({
      id: entry.id,
      title: entry.title,
      markdown,
    });
  }

  return contentEntries;
}

await buildCatalog();
